[connections.gsheets]
spreadsheet = "LINK_DA_SUA_PLANILHA_AQUI"
type = "service_account"
project_id = "COPIE_DO_JSON"
private_key_id = "COPIE_DO_JSON"
private_key = "COPIE_DO_JSON"
client_email = "COPIE_DO_JSON"
client_id = "COPIE_DO_JSON"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "COPIE_DO_JSON"