[theme]
primaryColor = "#D8436B"    # Um rosa framboesa elegante para os botões
backgroundColor = "#FFFDF9" # Um creme bem clarinho (cor de farinha/leite)
secondaryBackgroundColor = "#FCEADE" # Um tom pêssego/pastel para o menu lateral
textColor = "#4A3B32"       # Um marrom café escuro para o texto (leitura fácil)
font = "sans serif"