[theme]
primaryColor = "#8D6E63"    # Marrom Chocolate (Botões e destaques)
backgroundColor = "#FFF9F5" # Creme Suave (Fundo da página)
secondaryBackgroundColor = "#FCE4EC" # Rosa Pastel (Barra lateral)
textColor = "#3E2723"       # Marrom Café Escuro (Textos)
font = "sans serif"